[환불원정단 황수미] Add: product/views.py ProductListView 구현
wecode-bootcamp-korea/10-GetRefund-backend pull request #4
Opened 2020-08-09 05:41 UTC by ifyouseeksoomi

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [X] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2020-08-10 02:23 UTC, soheon-lee commented on product/urls.py
> +from .views import ProductListView
django Modul import 와 내 클래스 import 사이에는 빈 줄을 한 칸 띄워줍니다

2020-08-10 02:23 UTC, soheon-lee commented on product/urls.py
> +    path('/productlist', ProductListView.as_view())
RESTful URL에 맞춰 다시 한 번 생각해보세요 :)

2020-08-10 02:23 UTC, soheon-lee commented on product/views.py
> +            } for i in allproducts ]
`i`라는 변수명은 지칭하는 대상이 불명확합니다. 의미를 가늠할 수 있는 정확한 변수명을 사용하는 것이 보다 좋은 코드를 작성하는 시작점이 됩니당 :)

2020-08-10 02:23 UTC, soheon-lee commented on product/views.py
> +            return JsonResponse({'all_view' : allview}, status=200)
`all_view`라는 단어도 상품 데이터라는 의미로 이해하기 어렵습니다. 수정해주세요 ~

2020-08-10 10:10 UTC, ifyouseeksoomi commented on product/urls.py
> +    path('/productlist', ProductListView.as_view())
다시한번 생각하여 바꾸어보았습니다!

2020-08-10 10:10 UTC, ifyouseeksoomi commented on product/urls.py
> +from .views import ProductListView
넵 띄웠습니다~!

2020-08-10 10:21 UTC, ifyouseeksoomi commented on product/views.py
> +            } for i in allproducts ]
수정하였습니다. 다만 의미를 가늠할 수 있게 하는 것에 초점을 맞추다보니 조금 길어졌는데, 괜찮을지요?

2020-08-10 10:21 UTC, ifyouseeksoomi commented on product/views.py
> +            return JsonResponse({'all_view' : allview}, status=200)
allitem_list로 수정하였습니다!

2020-08-11 10:51 UTC, evergreen-david requested changes

2020-08-11 10:51 UTC, evergreen-david commented on product/urls.py
> +    path('/allitem-filter', FilterView.as_view())
allitem 엔드포인트 URL 이 좀 어색한거같아서 아래와같이 수정 부탁 드립니다. 
이미 product url로 라우팅 되고 있기 때문에 list 와 모든 item 이라는 것이 꼭 들어가야 하나 싶습니다.
```suggestion
    path('', ProductListView.as_view()),
    path('/filter', FilterView.as_view())
```

2020-08-11 10:51 UTC, evergreen-david commented
@ifyouseeksoomi comment address 한 이후에 resolve conversation 버튼 꼭 확인 해주세요!

2020-08-11 10:54 UTC, evergreen-david requested changes

2020-08-11 10:54 UTC, evergreen-david commented on product/views.py
> +            allproducts = Product.objects.prefetch_related("image_set").all()
```suggestion
            all_products = Product.objects.prefetch_related("image_set").all()
```

2020-08-11 10:54 UTC, evergreen-david commented on product/views.py
> +                categoryproducts = []
```suggestion
                category_products = []
```

2020-08-11 10:54 UTC, evergreen-david commented on product/views.py
> +                categoryproducts = []
category_products 리스트 컴프리헨션 사용해서 수정해보고 바랍니다.!

2020-08-11 10:54 UTC, evergreen-david commented on product/views.py
> +                applyingproducts = []
여기도 패턴이 반복되는데 리스트 컴프리헨션으로 바꿔보시기 바랍니다.

2020-08-11 10:54 UTC, evergreen-david commented on product/views.py
> +            } for categoryapplyingproduct in categoryapplyingproducts ]
categoryapplyingproduct 변수가 너무 길고 너무 길때는 _ 로 구분지어서 하면 훨씬 가독성이 좋아집니다.
지금 이함수 길이가 너무 길어서 그런데 helper function 만들어서 리펙토링 해주시기 바랍니다.

2020-08-11 10:59 UTC, ifyouseeksoomi commented on product/urls.py
> +    path('/allitem-filter', FilterView.as_view())
수정하였습니다.

2020-08-11 11:01 UTC, ifyouseeksoomi commented on product/views.py
> +            allproducts = Product.objects.prefetch_related("image_set").all()
수정하였습니다.

2020-08-13 02:24 UTC, evergreen-david requested changes

2020-08-13 02:24 UTC, evergreen-david commented on product/views.py
> +            categoryapplyingproducts = []
변수들 단어 단위로 언더스코어로 구분 해주면 좋을 것 같습니다.!

2020-08-13 07:24 UTC, ifyouseeksoomi commented on product/views.py
> +            categoryapplyingproducts = []
네 바꾸었습니다!

2020-08-13 07:58 UTC, evergreen-david commented
@ifyouseeksoomi 님 혹시 유닛테스트는 다른 PR에 있나요 ?

2020-08-13 09:55 UTC, ifyouseeksoomi commented on product/views.py
> +            } for categoryapplyingproduct in categoryapplyingproducts ]
상록님 혹시 이 함수라는게 어디를 말씀하시는걸까요?

2020-08-13 12:12 UTC, ifyouseeksoomi commented
> @ifyouseeksoomi 님 혹시 유닛테스트는 다른 PR에 있나요 ?

상록님 지금 계속 리팩토링 중인데.. 유닛테스트 아마 못할 것 같습니다 ㅠ 다음주엔 무조건 할건데 유닛테스트할 시간 여유가 아마 없을것으로 생각됩니다. ㅠㅠ

2020-08-13 14:54 UTC, lordmyshepherd approved these changes

2020-08-13 14:54 UTC, lordmyshepherd commented on product/views.py
> +            all_products = Product.objects.prefetch_related("image_set").all()
`products`

2020-08-13 14:54 UTC, lordmyshepherd commented on product/views.py
> +            products =[ {
`resutls`

2020-08-13 14:54 UTC, lordmyshepherd commented on product/views.py
> +                "model_img"          : product.image_set.get(image_category_id=2).image_url,
`image_category` table 부터 접근

2020-08-13 14:55 UTC, merged