[환불원정단 안솔] Add: product app detailview 구현
wecode-bootcamp-korea/10-GetRefund-backend pull request #5
Opened 2020-08-10 14:00 UTC by Sol-Ahn

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
Add: product app detailview 구현
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)
product/views.py에 ProductDetailView, PairWithView 작성
## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [X] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2020-08-11 11:00 UTC, evergreen-david requested changes

2020-08-11 11:00 UTC, evergreen-david commented on product/views.py
> +ImageCategory
파이썬 기본 indent 는 4칸 입니다.
정리 부탁 드리겠습니다.
```suggestion
    Product,
    Applying,
    Category,
    Color,
    Image,
    ImageCategory
```

2020-08-11 11:00 UTC, evergreen-david commented on product/views.py
> +        if not product_id > 17:
17이라는 숫자로 PRODUCT_LIMIT 과같은 변수로 정리해주세요.
왜냐하면 17이라는 숫자는 코드를 작성한 사람만 알기 때문에 추후에 보수 유지가 어렵습니다.

2020-08-11 11:00 UTC, evergreen-david commented on product/views.py
> +        pair_list      = []
pair_list 도 리스트 컴프리헨션으로 수정 부탁 드립니다.!

2020-08-11 11:00 UTC, evergreen-david commented on product/views.py
> +            if i.id < 18:
18이라는 숫자도 클래스 변수만들어서 사용해주세요

2020-08-11 11:00 UTC, evergreen-david commented on user/views.py
> +
파일 끝은 한줄만 남겨주세요.

2020-08-11 11:00 UTC, evergreen-david commented on product/views.py
> +                "id"            : i.id,
여기도 4칸 이상인것 같은데 윗줄대비 4칸만 띄워서 정리해주세요!

2020-08-12 01:32 UTC, evergreen-david requested changes

2020-08-12 01:32 UTC, evergreen-david commented on product/views.py
> +                product_list.append(i)
product_list 도 리스트 컴프리 헨션으로 고치면좋을것 같습니다.!

2020-08-12 01:32 UTC, evergreen-david commented on product/views.py
> +        if not product_id > PRODUCT_LIMIT:
if문이 부정문이라서 if product_id < PRODUCT_LIMIT: 로 고친다면 좀더 읽기 쉬운 코드가 될것 같습니다.

2020-08-12 01:32 UTC, evergreen-david commented on product/views.py
> +        if not product_id > PRODUCT_LIMIT:
if 문 else 문안에 명령문이 너무길어서 가독성이 좋지 않은데요.. 이부분 일단 color, image_set 을 합치고 경우에 따라서 데이터 구성하는부분만 helper function(내부 메서드) 만들어서 처리해주면 좋을 것 같습니다.
Product.objects.select_related("color","image_set").prefetch_related("image_set").get(id = product_id)
혹시 이해안되시면 꼭 질문해서 리펙토링 부탁 드리겠습니다.

2020-08-12 01:33 UTC, evergreen-david commented
@Sol-Ahn 님 그리고 comment address 하시면 꼭 resolve conversation 으로 더블첵 해주세요.

2020-08-13 12:33 UTC, Sol-Ahn commented
feature branch에 pull origin master를 하여 해당 branch에서 작업하지 않은 코드가 함께 올라갔습니다.

2020-08-13 13:45 UTC, lordmyshepherd approved these changes

2020-08-13 13:45 UTC, lordmyshepherd commented on order/views.py
> +            ).save
`save()`함수는 삭제해주세요.

2020-08-13 13:45 UTC, lordmyshepherd commented on order/views.py
> +        print(cart_item.quantity)
프린트 지워주세요~

2020-08-13 13:45 UTC, lordmyshepherd commented on order/views.py
> +        elif data['action'] == 'minus':
elif --> else로 바꿔주세요

2020-08-13 13:45 UTC, lordmyshepherd commented on product/views.py
> +            product = Product.objects.select_related("color").prefetch_related("image_set").get(id = product_id)
`product = Product.objects.select_related("color").prefetch_related("image_set").filter(id=product_id, group = product.group)`

2020-08-13 13:45 UTC, lordmyshepherd commented on product/views.py
> +            return JsonResponse({"data" : data})
status code를 추가해주세요

2020-08-13 13:45 UTC, merged